config/routes.rb
Kairos::Application.routes.draw do

  namespace :api do
    get '/users', to: 'users#index'
    get '/tags/skills', to: 'tags#skills'
  end

  # Static Pages
  get '/about', to: 'statics#about', as: 'about'
  get '/fellows', to: 'statics#fellows', as: 'fellows'
  get '/contact', to: 'statics#contact', as: 'contact'
  post '/contact_us', to: 'statics#contact_us'

  root to: 'statics#about'

  resources :projects, except: [:destroy] do
    resources :images
    resources :comments
  end

  resources :articles, except: [:destroy] do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :edit, :update]
  get '/dashboard', to: 'users#dashboard', as: :user_root
  put '/user/:id/approve', to: 'users#approve', as: :approve_user
  get '/unapproved_users', to: 'users#unapproved_users', as: :unapproved_users
  get '/search_users', to: 'users#search', as: :users_search

  resources :events, except: [:destroy] do
    resources :comments
  end

  resources :project_event_registrations, only: [:create, :destroy]
  resources :user_event_registrations, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy]

  resources :user_projects, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :skills
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  validates_uniqueness_of :username

  include FlagShihTzu
  # The keys must not be changed once in use, or you will get incorrect results.
  # maximum flag is 16
  has_flags 1 => :clean_tech, 2 => :health_care, 3 => :big_data, 4 => :information_technology_and_services, 5 => :venture_capital_and_private_equity, 6 => :management_consulting, 7 => :government_administration, 8 => :biomedical_sciences, 9 => :medical_devices, 10 => :education, 11 => :professional_training_and_coaching, 12 => :media_production, 13 => :non_profit_organization, 14 => :artificial_intelligence, 15 => :logistics_and_supply_chain, 16 => :others, column: 'industries'

  INDUSTRIES = {
    'clean_tech'                          => 'Clean Tech',
    'health_care'                         => 'Health Care',
    'big_data'                            => 'Big Data',
    'information_technology_and_services' => 'Information Technology and Services',
    'venture_capital_and_private_equity'  => 'Venture Capital and Private Equity',
    'management_consulting'               => 'Management Consulting',
    'government_administration'           => 'Government Administration',
    'biomedical_sciences'                 => 'Biomedical Sciences',
    'medical_devices'                     => 'Medical Devices',
    'education'                           => 'Education',
    'professional_training_and_coaching'  => 'Professional Training and Coaching',
    'media_production'                    => 'Media Production',
    'non_profit_organization'             => 'Non Profit Organization',
    'artificial_intelligence'             => 'Artificial Intelligence',
    'logistics_and_supply_chain'          => 'Logistics and Supply Chain',
    'others'                              => 'Others'
  }

  def industries
    industries = []
    INDUSTRIES.each do |key, industry|
      industries << industry if self.send(key)
    end
    industries
  end

  validates :member_type, inclusion: %w(mentor innovator committee)
  validates_presence_of :company,
    :job_title,
    :biography,
    :username,
    :first_name,
    :last_name,
    :email,
    :age,
    :involvement_in_asean,
    :problem_solving_skills,
    :contribution_to_society,
    :leadership_quality,
    :industry_expertise,
    :vision,
    :entrepreneurial

  scope :approved, -> {where('approved = ?', true)}
  scope :unapproved, -> {where('approved = ?', false)}

  has_attached_file :avatar,
    styles: {
      medium: '300x300>',
      thumb: '100x100>'
    },
    default_url: 'images/missing_user.png'

  validates_attachment :avatar,
    presence: true,
    content_type: {
      content_type: ['image/png', 'image/jpg', 'image/jpeg'],
      message: 'must be of .png, .jpg, or .jpeg format.'
    },
    size: { in: 0..2.megabytes, message: 'must be smaller than 2 megabytes.' }

  def thumb_url
    avatar.url(:thumb)
  end

  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :comments
  has_many :articles

  has_many :user_event_registrations
  has_many :registered_events, through: :user_event_registrations, source: :event

  has_many :user_projects
  has_many :projects, through: :user_projects

  has_many :votes

  has_many :events

  belongs_to :country

  belongs_to :referrer, class_name: 'User', foreign_key: 'referred_by_id'
  has_many :referred_members, class_name: 'User', foreign_key: 'referred_by_id'

  def registered_for_event?(event)
    user_event_registrations.map(&:event_id).include?(event.id)
  end

  def has_voted_for?(project, event)
    registration = ProjectEventRegistration.find_by_project_id_and_event_id(project.id, event.id)
    Vote.where(project_event_registration_id: registration.id, user_id: id).count != 0
  end

  def name
    "#{first_name} #{last_name}"
  end

  def avatar_url(size=:thumb)
    avatar.url size
  end

  def serializable_hash
    super(
      methods: [
        :skill_list,
        :avatar_url
      ],
      except: [
        :created_at,
        :updated_at,
        :admin,
        :approved,
      ])
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    @users = User.approved.map &:serializable_hash
    render json: @users, status: :ok
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  prepend_before_filter :require_no_authentication, only: [:cancel]
  before_filter :update_sanitized_params, if: :devise_controller?

  before_action :get_skill_list, only: [:new, :create]

  def create
    # FIXME: Of course this is not nice, fix this when you have time. Move this into a Service?
    industries = params[:user].delete(:industries).reject {|i| i.blank?}.map {|i| i.downcase.parameterize.underscore}
    build_resource(sign_up_params)
    industries.each {|industry| resource.send("#{industry}=", true)}

    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        sign_up(resource_name, resource)
        #NOTE: Hacky way to sign user out after signing up. Do not want to spend
        #too much time in devise documentation.
        Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)

        flash[:notice] = t(:'users.member_request_submitted')
        redirect_to root_url
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  private

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(
       :username,
       :first_name,
       :last_name,
       :email,
       :password,
       :password_confirmation,
       :member_type,
       :company,
       :job_title,
       :biography,
       :avatar,
       :industries,
       :linkedin_url,
       :country_id,
       :age,
       :involvement_in_asean,
       :problem_solving_skills,
       :contribution_to_society,
       :leadership_quality,
       :industry_expertise,
       :vision,
       :entrepreneurial,
       skill_list: []
      )
    end
  end

  def get_skill_list
    @skills = ActsAsTaggableOn::Tag.where tag_type: "skill"
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    #NOTE: Hacky way to redirect user if he is not approved. Do not want to spend
    #too much time in devise documentation.
    user = User.find_by_email(params['user']['email'])
    if !user.approved
      flash[:alert] = t(:'common.not_yet_approved')
      return redirect_to root_url
    end

    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    set_flash_message(:notice, :signed_in) if is_flashing_format?
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_approved_current_user
  before_filter :authenticate_admin, only: [:unapproved_users]
  before_filter :get_skill_list, only: [:edit, :update]

  def show
    @user = User.includes([{articles: :comments}, :projects]).friendly.find(params[:id])
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def update
    #FIXME: This piece of code is written at 12am after Manchester United lost 3-0 to Liverpool, home game. Bare with me.
    industries = params[:user].delete(:industries).reject {|i| i.blank?}.map {|i| i.downcase.parameterize.underscore}
    @user = User.friendly.find(params[:id])
    @user.industries.each {|industry| @user.send("#{industry.downcase.parameterize.underscore}=", false)}
    industries.each {|industry| @user.send("#{industry}=", true)}

    if @user.update_attributes(user_params)
      flash[:notice] = t(:'users.profile_updated')
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  #NOTE: unapproved_users and approve should be in admin controller, but I really have no time to do this now.
  def unapproved_users
    @users = User.unapproved
  end

  def approve
    user = User.find(params[:id])
    user.update_attributes(approved: true)
    EmailWorker.perform_async('ContactUsMailer', :user_approved, {email: user.email, name: user.first_name})
    render json: {}, status: :ok
  end

  def dashboard
    @events = Event.registerable.order('starts_at DESC')
    @users = User.approved
    @projects = Project.all.order('created_at DESC')
    @articles = Article.all.order('created_at DESC')
  end

  def search
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :username,
      :email,
      :password,
      :password_confirmation,
      :remember_me,
      :member_type,
      :company,
      :job_title,
      :linkedin_url,
      :biography,
      :country_id,
      :referred_by_id,
      :avatar,
      skill_list: []
    )
  end

  def get_skill_list
    @skills = ActsAsTaggableOn::Tag.where tag_type: "skill"
  end
end

app/views/users/_form.html.erb
<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :username, class: "required" %><br />
  <%= f.text_field :username, autofocus: true, class: 'form-control', required: true %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :first_name, class: "required" %><br />
  <%= f.text_field :first_name, class: 'form-control', required: true %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :last_name, class: "required" %><br />
  <%= f.text_field :last_name, class: 'form-control', required: true %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :email, class: "required" %><br />
  <%= f.email_field :email, class: 'form-control', required: true %>
<% end %>

<% if !edit %>
  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :password, class: "required" %><br />
    <%= f.password_field :password, autocomplete: 'off', class: 'form-control', required: true %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :password_confirmation, class: "required" %><br />
    <%= f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control', required: true %>
  <% end %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :member_type %><br />
  <%= f.select :member_type, options_for_select(%w{mentor innovator committee}, 'innovator'), class: 'member-type' %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :company, class: "required" %><br />
  <%= f.text_field :company, class: 'form-control', required: true %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :job_title, class: "required" %><br />
  <%= f.text_field :job_title, class: 'form-control', required: true %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :linkedin_url %><br />
  <%= f.text_field :linkedin_url, class: 'form-control' %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :biography, class: "required" %>
  <%= f.text_area :biography, class: 'form-control tinymce tinymce-text-area', required: true %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :industries %>
  <%= f.select :industries,
    User::INDUSTRIES.values,
    {},
    { multiple: true, id: 'user-industries' } %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :skill_list, t(:'users.skills') %>
  <%= f.select :skill_list,
    @skills,
    {},
    { multiple: true, id: 'user-skills' } %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :country_id, 'Country' %>
  <%= f.select :country_id,
    Country.all.collect {|c| [c.name, c.id] },
    {},
    { id: 'user-country' } %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :referred_by_id, 'Referrer' %>
  <%= f.select :referred_by_id,
    User.all.collect {|u| [u.name, u.id] },
    {},
    { id: 'user-referred-by' } %>
<% end %>

<%= content_tag :div, class: 'form-group' do %>
  <%= f.label :avatar, t(:'users.profile_picture'), class: "required" %>
  <%= f.file_field :avatar, required: true %>
<% end %>

app/views/users/dashboard.html.erb
<div class='container'>
  <h1>
    <%= t(:'users.dashboard') %>
    <%= link_to t(:'projects.add_your_startup'), new_project_url, class: 'pull-right btn btn-info', style: 'margin-left: 10px' %>
    <%= link_to t(:'articles.write_an_article'), new_article_url, class: 'pull-right btn btn-success' %>
  </h1>
  <div class='row'>
    <div class='col-md-7'>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t(:'events.upcoming') %></h3>
        </div>
        <div class="panel-body tab-content-container-fixed">
          <ul id='dashboard-events'>
            <% @events.each do |event| %>
              <li>
                <%= link_to event_url(event), style: 'font-size: 18px;' do %>
                  <%= event.name %>
                  <span class='pull-right'>
                    <%= event.starts_at.to_date.to_formatted_s(:long) %>
                    <%= t(:'common.at') %>
                    <%= event.venue_name %>
                  </span>
                <% end %>
                <%= event.description.html_safe %>
              </li>
              <hr class='featurette'>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class='col-md-5'>
      <div class='panel panel-success'>
        <div class='panel-heading'>
          <h3 class='panel-title'>
            <%= t(:'articles.articles') %>
          </h3>
        </div>
        <div class='panel-body tab-content-container-fixed'>
          <%= render partial: 'articles/articles_tab', locals: {articles: @articles} %>
        </div>
      </div>
    </div>
  </div>
</div>



<div class='container'>
  <div class='row'>
    <div class='col-md-7'>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= t(:'users.community') %>
            <%= link_to t(:'users.advanced_search'), users_search_url, class: 'pull-right' %>
          </h3>
        </div>
        <div class="panel-body tab-content-container-fixed">
          <ul id='dashboard-users'>
            <% @users.each do |user| %>
              <li>
                <div class='row'>
                  <div class='col-md-5'>
                    <%= link_to user_url(user), style: 'font-size: 13px;' do %>
                      <%= image_tag user.avatar.url(:thumb), class: 'small-img' %>
                      <%= user.first_name && user.last_name ?
                        truncate("#{user.first_name} #{user.last_name}", length: 15) : truncate(user.username, length: 15) %>
                  </div>
                  <div class='col-md-7' style='margin-top:15px;'>
                    <span>
                      <%= user.company %>
                      <span class='label label-success'><%= user.member_type %></span>
                    </span>
                  </div>
                  <% end %>
                </div>
              </li>
              <br />
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class='col-md-5'>
      <div class='panel panel-info'>
        <div class='panel-heading'>
          <h3 class='panel-title'>
            <%= t(:'projects.startups') %>
            <%= link_to t(:'projects.add_your_startup'), new_project_url, class: 'pull-right' %>
          </h3>
        </div>
        <div class='panel-body tab-content-container-fixed'>
          <%= render partial: 'projects/projects_tab', locals: {projects: @projects} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container well'>
  <div class='row'>
    <div class='col-xs-12 col-sm-6 col-md-8'>
      <h2><%= t(:'users.edit_profile') %></h2>

      <%= form_for @user, html: { role: 'form', multipart: true } do |f| %>
        <%= render partial: 'shared/errors', locals: {object: @user} %>

        <%= render partial: 'form', locals: {f: f, edit: true} %>

        <div>
          <%= f.submit t(:'common.save'), class: 'btn btn-success' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<%= tinymce_assets %>
<%= tinymce %>

app/views/users/search.html.haml
.container(data-bind="with: UserSearchViewModel")
  .row
    .col-md-12
      .panel.panel-success
        .panel-heading
          %h3.panel-title Search
        .panel-body
          Search By Skills
          %select#user-search(data-bind="options: skillList, optionsText: 'name', optionsValue: 'name', selectedOptions: filters" multiple=true)
        .panel-body.tab-content-container-fixed
          %ul#dashboard-users(data-bind="foreach: users")
            %li.user-row
              .row
                -# .col-md-5
                .col-md-12
                  %a(data-bind="attr: { href: url }" style="font-size: 30px;")
                    %img.small-img(data-bind="attr: { src: imageURL }")
                    %span.display-name(data-bind="text: displayName")
                -# .col-md-7(style="margin-top: 15px;")

:javascript
  $(document).ready(function() {
      ko.applyBindings();
  });

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <% if @user.id == current_user.id %>
      <div class='pull-right'>
        <%= link_to t(:'users.change_your_password'), edit_user_registration_path, class: 'btn btn-success' %>
        <%= link_to t(:'users.edit_profile'), edit_user_url(@user), class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div><br />

<div class="container">
  <div class='jumbotron' id='user-profile'>
    <div class="pull-left" id='user-info'>
      <h2 class="media-heading"><%= @user.first_name %> <%= @user.last_name %></h2>
      <h4><%= @user.job_title %> at <%= @user.company %></h4>
      <h4><%= @user.email %></h4>
      <% if @user.linkedin_url %>
        <h4><i class="fa fa-linkedin-square"></i> <a href="<%= @user.linkedin_url %>" target='_blank'>Linkedin Profile</a></h4>
      <% end %>
      <h4><%= @user.country.try(:name) %></h4>
      <% if @user.referrer %>
        <h4>Referred By <%= "#{@user.referrer.first_name} #{@user.referrer.last_name}" %></h4>
      <% end %>
      <hr style="margin:8px auto">

      <div id='user-labels'>
        <span class="label label-primary"><%= @user.member_type %></span>
        <% @user.industries.each do |industry| %>
          <span class='label label-success'><%= industry %></span>
        <% end %>
      </div>
    </div>
    <div class="pull-right">
      <%= image_tag @user.avatar.url(:medium), style: 'width: 200px; height: 200px;' %>
    </div>
  </div>
</div>

<div class='container'>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-tabs-container">
    <li class='active'><a href="#biography" data-toggle="tab">Biography</a></li>
    <li><a href="#projects" data-toggle="tab"><%= t(:'projects.projects') %></a></li>
    <li><a href="#articles" data-toggle="tab"><%= t(:'articles.articles') %></a></li>
    <% if current_user.admin %>
      <li><a href="#interview-answers" data-toggle="tab"><%= t(:'users.answers') %></a></li>
    <% end %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content tab-content-container">
    <div class="tab-pane active" id="biography">
      <%= @user.biography.html_safe %>
    </div>
    <div class="tab-pane" id="projects">
      <ul id='user-projects'>
        <% @user.projects.each do |project| %>
          <li class='user-project'>
            <%= link_to project.title, project_url(project), class: 'user-project-link' %>
            <% project.tags.each do |tag| %>
              <span class='label label-info'><%= tag.name %></span>
            <% end %>
            <hr class="featurette-divider">
          </li>
        <% end %>
      </ul>
    </div>
    <div class="tab-pane" id="articles">
      <%= render partial: 'articles/articles_tab', locals: {articles: @user.articles} %>
    </div>
    <% if current_user.admin %>
      <div class="tab-pane" id="interview-answers">

        <div id="age" class="interview-question"><%= t(:'users.age_question') %></div>
        <div class="interview-answer"><%= @user.age %></div>

        <div id="involvement-in-asean" class="interview-question"><%= t(:'users.involvement_in_asean_question') %></div>
        <div class="interview-answer"><%= @user.involvement_in_asean %></div>

        <div id="problem-solving-skills" class="interview-question"><%= t(:'users.problem_solving_skills_question') %></div>
        <div class="interview-answer"><%= @user.problem_solving_skills %></div>

        <div id="contribution-to-society" class="interview-question"><%= t(:'users.contribution_to_society_question') %></div>
        <div class="interview-answer"><%= @user.contribution_to_society %></div>

        <div id="leadership-quality" class="interview-question"><%= t(:'users.leadership_quality_question') %></div>
        <div class="interview-answer"><%= @user.leadership_quality %></div>

        <div id="industry-expertise" class="interview-question"><%= t(:'users.industry_expertise_question') %></div>
        <div class="interview-answer"><%= @user.industry_expertise %></div>

        <div id="vision" class="interview-question"><%= t(:'users.vision_question') %></div>
        <div class="interview-answer"><%= @user.vision %></div>

        <div id="entrepreneurial" class="interview-question"><%= t(:'users.entrepreneurial_question') %></div>
        <div class="interview-answer"><%= @user.entrepreneurial %></div>

      </div>
    <% end %>
  </div>
</div>

app/views/users/unapproved_users.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Unapproved Users</h3>
        </div>
        <div class="panel-body tab-content-container-fixed">
          <ul id='dashboard-users'>
            <% @users.each do |user| %>
              <li>
                <div class='row'>
                  <div class='col-md-5'>
                    <%= link_to user_url(user), style: 'font-size: 13px;' do %>
                      <%= image_tag user.avatar.url(:thumb), class: 'small-img' %>
                      <%= user.first_name && user.last_name ?
                        truncate("#{user.first_name} #{user.last_name}", length: 15) : truncate(user.username, length: 15) %>
                  </div>
                  <div class='col-md-7' style='margin-top:15px;'>
                    <span><%= user.company %></span>
                    <%= link_to 'Approve User', approve_user_url(user.id), class: 'btn btn-success', method: :put, remote: true %>
                  </div>
                  <% end %>
                </div>
              </li>
              <br />
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<script type='text/javascript'>
    $("a[data-remote]").on("ajax:success", function(e, data, status, xhr){
        var message = HandlebarsTemplates['alerts/success']({
          message: 'This user has been approved'
        });
        $('#notification').append(message);
        clearNotification();
        $(this).parents('li').remove();
    });
</script>