config/routes.rb
Kairos::Application.routes.draw do

  namespace :api do
    get '/users', to: 'users#index'
    get '/tags/skills', to: 'tags#skills'
  end

  # Static Pages
  get '/about', to: 'statics#about', as: 'about'
  get '/fellows', to: 'statics#fellows', as: 'fellows'
  get '/contact', to: 'statics#contact', as: 'contact'
  post '/contact_us', to: 'statics#contact_us'

  root to: 'statics#about'

  resources :projects, except: [:destroy] do
    resources :images
    resources :comments
  end

  resources :articles, except: [:destroy] do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :edit, :update]
  get '/dashboard', to: 'users#dashboard', as: :user_root
  put '/user/:id/approve', to: 'users#approve', as: :approve_user
  get '/unapproved_users', to: 'users#unapproved_users', as: :unapproved_users
  get '/search_users', to: 'users#search', as: :users_search

  resources :events, except: [:destroy] do
    resources :comments
  end

  resources :project_event_registrations, only: [:create, :destroy]
  resources :user_event_registrations, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy]

  resources :user_projects, only: [:create, :destroy]

end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class='alert alert-danger'>
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
     <br />
     <div class='pull-left'>
       <%= image_tag 'k-logo.png' %>
       <div>© 2014 The Kairos Society<br /> All Rights Reserved.</div>
    </div>
    <div class='pull-right'>
      <%= image_tag 'footer-logos.png' %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: 'navbar-brand' do %>
        <%= image_tag('kairosfb.png', id: 'kairos-logo') %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to t(:'users.dashboard'), user_root_url %></li>
        <% end %>
        <li><%= link_to t(:'common.about'), about_url %></li>
        <li><%= link_to t(:'common.members'), fellows_url %></li>
        <% if current_user.try(:admin) %>
          <li><%= link_to 'Unapproved Users', unapproved_users_url %></li>
        <% end %>
        <!--<li><%#= link_to t(:'common.news'), '#' %></li>-->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.username, user_url(current_user) %></li>
          <li><%= link_to t(:'common.sign_out'), destroy_user_session_url, method: :delete %></li>
        <% else %>
          <li><%= link_to t(:'common.sign_in'), new_user_session_url %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>