config/routes.rb
Kairos::Application.routes.draw do

  namespace :api do
    get '/users', to: 'users#index'
    get '/tags/skills', to: 'tags#skills'
  end

  # Static Pages
  get '/about', to: 'statics#about', as: 'about'
  get '/fellows', to: 'statics#fellows', as: 'fellows'
  get '/contact', to: 'statics#contact', as: 'contact'
  post '/contact_us', to: 'statics#contact_us'

  root to: 'statics#about'

  resources :projects, except: [:destroy] do
    resources :images
    resources :comments
  end

  resources :articles, except: [:destroy] do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :edit, :update]
  get '/dashboard', to: 'users#dashboard', as: :user_root
  put '/user/:id/approve', to: 'users#approve', as: :approve_user
  get '/unapproved_users', to: 'users#unapproved_users', as: :unapproved_users
  get '/search_users', to: 'users#search', as: :users_search

  resources :events, except: [:destroy] do
    resources :comments
  end

  resources :project_event_registrations, only: [:create, :destroy]
  resources :user_event_registrations, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy]

  resources :user_projects, only: [:create, :destroy]

end

app/models/event.rb
class Event < ActiveRecord::Base
  MAX_PROJECT_PARTICIPANTS = 5
  MAX_PARTICIPANTS = 40

  validates_presence_of :name, :description, :starts_at, :ends_at, :venue_name, :street_one, :city, :country, :user_id
  validate :starts_at_must_be_before_ends_at

  has_many :user_event_registrations
  has_many :project_event_registrations
  has_many :projects, through: :project_event_registrations

  has_many :comments, as: :commentable, dependent: :destroy

  belongs_to :user

  extend FriendlyId
  friendly_id :name, use: :slugged

  scope :registerable, -> {where('starts_at > ?', Date.today)}

  def starts_at_must_be_before_ends_at
    errors.add(:starts_at, 'must be before ends at') unless starts_at < ends_at
  end

  geocoded_by :address
  after_validation :geocode

  def address
    [street_one, street_two, city, state, country, zip_code].compact.join(', ')
  end

  ADDRESS_COMPONENTS = [:street_one, :street_two, :city, :state, :country, :zip_code]
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_approved_current_user
  before_filter :verify_committee, except: [:show]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      EmailWorker.perform_async('EventMailer', :new_event_notification, {event_id: @event.id, host_with_port: request.host_with_port})
      redirect_to event_url(@event)
    else
      render :new
    end
  end

  def show
    @event = Event.includes(:projects).friendly.find(params[:id])
    @comment = Comment.new

    @user_registration_id = UserEventRegistration.find_by_user_id_and_event_id(current_user.id, params[:id]).try(:id) || 0
    @project_registration_id = ProjectEventRegistration.of_user_and_event(current_user.id, params[:id]).try(:id) || 0

    @event_attendees = UserEventRegistration.includes(:user).where(event_id: params[:id]).map(&:user)
  end

  def edit
    @event = Event.friendly.find(params[:id])
  end

  def update
    @event = Event.friendly.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:notice] = t(:'events.event_updated')
      redirect_to event_url(@event)
    else
      render :edit
    end
  end

  private

  def event_params
    params.require(:event).permit(
      :name,
      :description,
      :starts_at,
      :ends_at,
      :venue_name,
      :street_one,
      :street_two,
      :city,
      :state,
      :country,
      :zip_code
    )
  end

  # Probably should be in Application Controller or another file.
  def verify_committee
    unless current_user.try(:member_type) == 'committee'
      flash[:alert] = t(:'common.no_right')
      redirect_to root_url
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class='container'>
  <h1><%= t(:'events.edit_event') %></h1>
  <div class='well'>
    <div class='row'>
      <div class='col-xs-12 col-sm-6 col-md-10'>

        <%= form_for @event, html: { role: 'form' } do |f| %>

          <%= render partial: 'shared/errors', locals: {object: @event} %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control tinymce tinymce-text-area' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :starts_at %><br />
            <%= f.date_select :starts_at, start_year: Time.now.year, end_year: Time.now.year + 5 %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.time_select :starts_at,
              ignore_date: true,
              minute_step: 15,
              ampm: true %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :ends_at %><br />
            <%= f.date_select :ends_at, start_year: Time.now.year, end_year: Time.now.year + 5 %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.time_select :ends_at,
              ignore_date: true,
              minute_step: 15,
              ampm: true %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :venue_name %><br />
            <%= f.text_field :venue_name, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :street_one %><br />
            <%= f.text_field :street_one, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :street_two %><br />
            <%= f.text_field :street_two, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :city %><br />
            <%= f.text_field :city, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :state %><br />
            <%= f.text_field :state, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :country %><br />
            <%= f.text_field :country, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :zip_code %><br />
            <%= f.text_field :zip_code, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
           <%= f.submit t(:'common.save'), class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= tinymce_assets %>
<%= tinymce %>

app/views/events/new.html.erb
<div class='container'>
  <h1><%= t(:'events.new_event') %></h1>
  <div class='well'>
    <div class='row'>
      <div class='col-xs-12 col-sm-6 col-md-10'>

        <%= form_for @event, html: { role: 'form' } do |f| %>

          <%= render partial: 'shared/errors', locals: {object: @event} %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control tinymce tinymce-text-area' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :starts_at %><br />
            <%= f.date_select :starts_at, start_year: Time.now.year, end_year: Time.now.year + 5 %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.time_select :starts_at,
              ignore_date: true,
              minute_step: 15,
              ampm: true %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :ends_at %><br />
            <%= f.date_select :ends_at, start_year: Time.now.year, end_year: Time.now.year + 5 %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.time_select :ends_at,
              ignore_date: true,
              minute_step: 15,
              ampm: true %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :venue_name %><br />
            <%= f.text_field :venue_name, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :street_one %><br />
            <%= f.text_field :street_one, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :street_two %><br />
            <%= f.text_field :street_two, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :city %><br />
            <%= f.text_field :city, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :state %><br />
            <%= f.text_field :state, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :country %><br />
            <%= f.text_field :country, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :zip_code %><br />
            <%= f.text_field :zip_code, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
           <%= f.submit t(:'common.create'), class: 'btn btn-success' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= tinymce_assets %>
<%= tinymce %>

app/views/events/show.html.erb
<% if @event.user_id == current_user.id %>
  <div class='container'>
    <div class='pull-right'>
      <%= link_to t(:'events.edit_event'), edit_event_url(@event), class: 'btn btn-info' %>
    </div>
  </div>
<% end %>

<div class='container'>
  <h1 class='pull-left'><%= @event.name %></h1>
  <div class='register pull-right'>
    <div class='row user-project-register'>
      <div class='user-event col-md-5' data-bind='with: UserRegisterEventViewModel'>
        <%= link_to t(:'register.individual'),
          '#',
          class: 'btn btn-success user-register-event',
          data: {bind: 'click: registerUser, visible: noUserRegisteredEvent()', 'user-id' => current_user.id, 'event-id' => @event.id} %>
        <%= link_to t(:'unregister.individual'),
          '#',
          class: 'btn btn-info user-unregister-event',
          data: {bind: 'click: unregisterUser, visible: !noUserRegisteredEvent()', id: @user_registration_id} %>
      </div>

      <div class='project-event col-md-5' data-bind='with: ProjectRegisterEventViewModel'>
        <%= link_to t(:'register.project'),
          '#',
          class: 'btn btn-info project-register-event',
          data: {bind: 'click: showSelectProjectForm, visible: noProjectRegisteredEvent()'} %>
        <%= link_to t(:'unregister.project'),
          '#',
          class: 'btn btn-success project-unregister-event',
          data:{bind: 'click: unregisterProject, visible: !noProjectRegisteredEvent()', id: @project_registration_id} %>
      </div>
      <br />
    </div>
    <div class='row'>
      <div id='select-project-form'>
        <%= select_tag 'Projects', options_from_collection_for_select(current_user.projects, 'id', 'title'), id: 'project-event-select' %>
        <%= link_to t(:'register.choose_project'),
          '#',
          class: 'btn btn-success project-register-event-final',
          data: {'event-id' => @event.id} %>
      </div>
    </div>
  </div>

  <div style='width: 100%;' data-bind='with: EventMapViewModel' id='event-map-container'>
    <div id="event-map"
      style='width: 100%; height: 400px;'
      data-latitude='<%= @event.latitude %>' data-longitude='<%= @event.longitude %>'>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class='panel-group' id='accordion'>
    <div id='event-description' class='panel panel-success'>
      <div class='panel-heading'>
        <h4 class='panel-title'>
          <a data-toggle='collapse' data-parent='#accordion' href='#collapseOne'>
            <%= t(:'events.description') %><i class="fa fa-arrow-down pull-right"></i>
          </a>
        </h4>
      </div>
      <div id='collapseOne' class='panel-collapse collapse in'>
        <div class='panel-body'>
          <%= @event.description.html_safe %>
        </div>
      </div>
    </div>

    <div id='event-venue' class='panel panel-primary'>
      <div class='panel-heading'>
        <h4 class='panel-title'>
          <a data-toggle='collapse' data-parent='#accordion' href='#collapseTwo'>
            <%= t(:'events.location') %><i class="fa fa-arrow-down pull-right"></i>
          </a>
        </h4>
      </div>
      <div id='collapseTwo' class='panel-collpase collapse'>
        <div class='panel-body'>
          <h3><%= @event.venue_name %></h3>
          <address class='event-address'>
            <% Event::ADDRESS_COMPONENTS.each do |component| %>
              <% if @event.send(component) %>
                <div><%= @event.send(component) %></div>
              <% end %>
            <% end %>
          </address>
        </div>
      </div>
    </div>

    <div id='event-attendees' class='panel panel-info'>
      <div class='panel-heading'>
        <h4 class='panel-title'>
          <a data-toggle='collapse' data-parent='#accordion' href='#collapseThree'>
            <%= t(:'events.attendees') %><i class="fa fa-arrow-down pull-right"></i>
          </a>
        </h4>
      </div>
      <div id='collapseThree' class='panel-collpase collapse'>
        <div class='panel-body'>
          <% @event_attendees.each do |attendee| %>
            <%= link_to user_url(attendee) do %>
              <%= image_tag attendee.thumb_url,
                class: 'event-attendee',
                data: {toggle: 'tooltip', placement: 'bottom', title: attendee.username} %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>

  <% if @event.projects.length > 0 %>
    <h3><%= t(:'register.event_registrants') %></h3>
    <ul class='event-project-registrants'>
      <% @event.projects.each do |project| %>
        <li class='project-registrant' id='project-"<%= project.id %>"'>
          <%= link_to project.title, project_url(project) %>
          <% if !current_user.has_voted_for?(project, @event) %>
            <a class='btn btn-success vote' data-event-id="<%= @event.id %>" data-project-id="<%= project.id %>">Vote for This Project</a>
          <% else %>
            <a class='btn btn-info unvote' data-event-id="<%= @event.id %>" data-project-id="<%= project.id %>">Unvote for This Project</a>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= render partial: 'comments/comments', object: @event.comments %>
  <%= render partial: 'comments/new', locals: { parent: @event } %>
</div>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script type='text/javascript'>
    $(document).ready(function (){
        //FIXME: Still need to move voting logic into ViewModel...don't be lazy please
        $('.project-registrant').on('click', '.vote', function(event) {
            var that = this;
            event.preventDefault();
            var eventId = $(that).attr('data-event-id');
            var projectId = $(that).attr('data-project-id');

            $.ajax({
                url: '/votes',
                type: 'POST',
                data: { vote: {project_id: projectId, event_id: eventId, user_id: <%= current_user.id %> }},
                dataType: 'json',
                success: function(data) {
                    $(that).after('<a class="btn btn-info unvote" data-project-id="' + projectId + '" data-event-id="' + eventId +'">Unvote for This Project</a>');
                    $(that).remove();
                    var message = HandlebarsTemplates['alerts/success']({
                      message: 'You have voted for the project!'
                    });
                   $('#notification').append(message);
                   $('html,body').animate({scrollTop:0},0);
                   clearNotification();
                }
            });
        });

        $('.project-registrant').on('click', '.unvote', function(event) {
            var that = this;
            event.preventDefault();
            var eventId = $(that).attr('data-event-id');
            var projectId = $(that).attr('data-project-id');

            $.ajax({
                //FIXME: I know this is cheating the routes and controller, but it's the fastest way for now
                url: '/votes/' + 0,
                type: 'DELETE',
                data: { vote: {project_id: projectId, event_id: eventId, user_id: <%= current_user.id %>}},
                dataType: 'json',
                success: function(data) {
                    $(that).after('<a class="btn btn-success vote" data-project-id="' + projectId + '" data-event-id="' + eventId +'">Vote for This Project</a>');
                    $(that).remove();
                    var message = HandlebarsTemplates['alerts/danger']({
                      message: 'You have unvoted for the project!'
                    });
                    $('#notification').append(message);
                    $('html,body').animate({scrollTop:0},0);
                    clearNotification();
                }
            });
        });

        $('.event-attendee').tooltip();

        $('.panel-heading').on('click', function() {
            var arrow = $(this).find('.fa');
            arrow.toggleClass('fa-arrow-up');
            arrow.toggleClass('fa-arrow-down');
        });
    });
</script>