config/routes.rb
Kairos::Application.routes.draw do

  namespace :api do
    get '/users', to: 'users#index'
    get '/tags/skills', to: 'tags#skills'
  end

  # Static Pages
  get '/about', to: 'statics#about', as: 'about'
  get '/fellows', to: 'statics#fellows', as: 'fellows'
  get '/contact', to: 'statics#contact', as: 'contact'
  post '/contact_us', to: 'statics#contact_us'

  root to: 'statics#about'

  resources :projects, except: [:destroy] do
    resources :images
    resources :comments
  end

  resources :articles, except: [:destroy] do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :edit, :update]
  get '/dashboard', to: 'users#dashboard', as: :user_root
  put '/user/:id/approve', to: 'users#approve', as: :approve_user
  get '/unapproved_users', to: 'users#unapproved_users', as: :unapproved_users
  get '/search_users', to: 'users#search', as: :users_search

  resources :events, except: [:destroy] do
    resources :comments
  end

  resources :project_event_registrations, only: [:create, :destroy]
  resources :user_event_registrations, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy]

  resources :user_projects, only: [:create, :destroy]

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates_presence_of :title, :description

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  has_many :project_event_registrations, dependent: :destroy
  has_many :registered_events, through: :project_event_registrations, source: :event

  has_many :user_projects, dependent: :destroy
  #FIXME: Members of a project, need a better name, but later
  has_many :users, through: :user_projects

  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_taggable
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_approved_current_user 
  before_action :get_user_ids, only: [:create, :update]
  before_action :get_all_tags_and_users, only: [:new, :edit]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      #FIXME: There must be a rails way of doing this nested join table thing
      create_user_projects(@project, @user_ids)
      flash[:notice] = t(:'projects.project_saved')
      redirect_to project_url(@project)
    else
      get_all_tags_and_users
      flash[:error] = t(:'common.error')
      render :new
    end
  end

  def edit
    @project = Project.friendly.find(params[:id])
  end

  def update
    @project = Project.friendly.find(params[:id])
    if @project.update_attributes(project_params)
      destroy_unwanted_users(@project, @user_ids)
      create_user_projects(@project, @user_ids)
      flash[:notice] = t(:'projects.project_updated')
      redirect_to project_url(@project)
    else
      get_all_tags_and_users
      render :edit
    end
  end

  def show
    @project = Project.includes(:tags).friendly.find(params[:id])
    @comment = Comment.new
  end

  private

  def project_params
    params.require(:project).permit(
      :title,
      :description,
      :youtube_video_id,
      images_attributes: [:avatar],
      tag_list: []
    )
  end

  def destroy_unwanted_users(project, user_ids)
    unwanted_user_ids = @project.users.map(&:id) - user_ids.map(&:to_i)
    UserProject.destroy_multiple_users(project.id, unwanted_user_ids)
  end

  def get_all_tags_and_users
    @tags = ActsAsTaggableOn::Tag.where(tag_type: "industry")
    @users = User.all
  end

  def get_user_ids
    @user_ids = get_nested_ids(:user_projects, :user_ids)
    @user_ids << current_user.id unless @user_ids.include?(current_user.id)
  end

  def create_user_projects(project, user_ids)
    UserProject.create_from_multiple_user_ids(project.id, user_ids)
  end

  def get_nested_ids(nested_params, nested_params_ids)
    params[:project].delete(nested_params)[nested_params_ids].split(', ')[0].reject(&:blank?)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_projects_tab.html.erb
<ul id='user-projects'>
  <% projects.each do |project| %>
    <li class='user-project'>
      <% if project.images.length > 0 %>
        <%= image_tag project.images.first.avatar.url(:thumb), class: 'small-img' %>
      <% else %>
        <%= image_tag 'default_article.jpg', class: 'small-img' %>
      <% end %>
      <%= link_to truncate(project.title, length: 18), project_url(project) %>
      <hr class="featurette-divider">
    </li>
  <% end %>
</ul>

app/views/projects/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12 col-sm-6 col-md-8'>
      <h1><%= t(:'projects.edit_project') %></h1>
      <div class='well'>
        <%= nested_form_for @project, html: { role: 'form', multipart: true } do |f| %>

          <%= render partial: 'shared/errors', locals: {object: @project} %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control tinymce tinymce-text-area' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>  
            <%= f.label :youtube_video_id, t(:'projects.youtube_video_id') %>
            <%= f.text_field :youtube_video_id, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :tag_list, t(:'projects.tags') %><br />
            <%= f.select :tag_list,
              @tags,
              {selected: @project.tag_list},
              {multiple: true, id: 'project-tag'} %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :user_projects, t(:'projects.team') %><br />
            <%= f.fields_for :user_projects do |pt| %>
              <%= pt.select 'user_ids',
                @users.collect { |t| [t.username, t.id] },
                {selected: @project.users.map(&:id)},
                {multiple: true, id: 'project-user'} %>
            <% end %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.submit t(:'common.save'), class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= tinymce_assets %>
<%= tinymce %>

app/views/projects/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12 col-sm-6 col-md-8'>
      <h1><%= t(:'projects.new_project') %></h1>
      <div class='well'>
        <%= nested_form_for @project, html: { role: 'form', multipart: true } do |f| %>

          <%= render partial: 'shared/errors', locals: {object: @project} %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control tinymce tinymce-text-area' %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :youtube_video_id, t(:'projects.youtube_video_id') %>
            <%= f.text_field :youtube_video_id, class: 'form-control' %>
          <% end %>

          <%= render partial: 'images/nested_form', locals: {f: f} %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :tag_list, t(:'projects.tags') %><br />
            <%= f.select :tag_list,
              @tags,
              {},
              {multiple: true, id: 'project-tag'} %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.label :user_projects, t(:'projects.team') %><br />
            <%= f.fields_for :user_projects do |pt| %>
              <%= pt.select 'user_ids',
                @users.collect { |t| [t.username, t.id] },
                {},
                { multiple: true, id: 'project-user' } %>
            <% end %>
          <% end %>

          <%= content_tag :div, class: 'form-group' do %>
            <%= f.submit t(:'common.create'), class: 'btn btn-success' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= tinymce_assets %>
<%= tinymce %>

app/views/projects/show.html.erb
<div class='container'>
  <div class='row'>
    <% unless @project.youtube_video_id.blank? %>
      <div id='project-video-controls' data-bind='with: ProjectVideoViewModel'>
        <span class='volume-on' data-bind='click: unmute'>
          <i class="fa fa-volume-up fa-3x"></i>
        </span>

        <span class='volume-off' data-bind='click: mute'>
          <i class="fa fa-volume-off fa-3x"></i>
        </span>

        <span class='pause' data-bind='click: pause'>
          <i class="fa fa-pause fa-3x"></i>
        </span>

        <span class='play' data-bind='click: play'>
          <i class="fa fa-play fa-3x"></i>
        </span>
      </div>
    <% end %>
    <% if @project.users.include?(current_user) %>
      <div class='pull-right' id='edit-project' style='margin-top: -40px'>
        <%= link_to t(:'projects.edit_project'), edit_project_url(@project), class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

<% unless @project.youtube_video_id.blank? %>
  <!-- FIXME: make the content into sections of different color -->
  <div id='project-video'>
    <a id="bgndVideo"
      class="player"
      data-property="{
        videoURL:'http://youtu.be/<%= @project.youtube_video_id %>',
        containment: 'body',
        autoPlay:true,
        mute:true,
        loop: true,
        startAt:0,
        opacity:1,
        showControls: false,
        showYTLogo: false,
        quality: 'highres'}">
    </a>
  </div>
<% end %>

<div class='row' id='project-container'>
  <div class='page-header'>
    <span class='startup-name'><%= @project.title %></span>
    <% @project.tags.each do |tag| %>
      <span class='label label-info startup-tag'><%= tag.name %></span>
    <% end %>
  </div>

  <h1><%= t(:'projects.description') %></h1>
  <div class='well'>
    <%= @project.description.html_safe %>
  </div>

  <% if @project.images.length > 0 %>
    <hr class="featurette-divider">
    <h1><%= t(:'projects.gallery') %><h1>
    <%= render_gallery_for @project.images %><br /><br />
  <% end %>

  <% if @project.users.length > 0 %>
    <hr class="featurette-divider">
    <h1><%= t(:'projects.team') %></h1>
    <% @project.users.each do |user| %>
      <%= link_to user_url(user) do %>
        <%= image_tag user.thumb_url,
          class: 'project-member',
          data: {toggle: 'tooltip', placement: 'bottom', title: "#{user.first_name} #{user.last_name}"} %>
      <% end %>
    <% end %>
  <% end %>

  <% if @project.contact_email || @project_number %>
    <hr class="featurette-divider">
    <h1><%= t(:'projects.contact_us') %></h1>
    <div class='list-group'>
      <a class='list-group-item'>
        <h4 class='list-group-item-heading'><%= t(:'common.email') %></h4>
        <p class='list-group-item-text'><%= @project.contact_email || t(:'projects.no_email') %></p>
      </a>
      <a class='list-group-item'>
        <h4 class='list-group-item-heading'><%= t(:'common.number') %></h4>
        <p class='list-group-item-text'><%= @project.contact_number || t(:'projects.no_number') %></p>
      </a>
    </div>
  <% end %>

  <%= render partial: 'comments/comments', object: @project.comments %>
  <%= render partial: 'comments/new', locals: { parent: @project } %>
</div>

<script type='text/javascript'>
    $(document).ready(function() {
        if ($('.player').length){
            $('.player').mb_YTPlayer();
        }
        $('.project-member').tooltip();
        //FIXME: This fixes the problem with the margin between the project content and footer,
        // showing parts of the video. But probably not the best solution?
        $('div#footer').css('margin-top', '0px');
        //FIXME: Another sloppy line of code to quickfix the alignment of edit project button,
        //Is it too trivial to have its own ViewModel to determine the visibility of a specific CSS class?
        if ($('#project-video-controls').length == 0){
            $('#edit-project').css('margin-top', '0px');
        }
    });
</script>